[project]
name = "py-rm"
version = "0.1.0"
description = "Provides the Result and Maybe monads for effective functional programming."
readme = "README.md"
authors = [
    { name = "Romeyus", email = "marco.possamai@proton.me" }
]
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

[tool.pyright]
extraPaths = ["src"]
typeCheckingMode = "strict"
ignore = ["**/__pycache__"]

[tool.pytest]
pythonpath = ["src"]
addopts = ["--import-mode=importlib"]
strict = true
